version: '3.9'

services:
  clients-db:
    image: bitnami/postgresql:16.2.0
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=clients
      - POSTGRES_PASSWORD=clients
      - POSTGRES_DB=clients_db
    volumes:
      - clients_data:/bitnami/postgresql
  transactions-db:
    image: bitnami/postgresql:16.2.0
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_USER=transactions
      - POSTGRES_PASSWORD=transactions
      - POSTGRES_DB=transactions_db
    volumes:
      - transactions_data:/bitnami/postgresql
  adminer:
    image: adminer:4.8.1
    restart: always
    ports:
      - 8080:8080

volumes:
  clients_data:
  transactions_data:
